### PR TITLE
Adds node-type-kafka, example and packaging deps

### PR DESCRIPTION
**Pull request by jpnorenam**
# Kafka {#node-type-kafka}

The @ref node-type-kafka node-type uses [librdkafka] to produce and consume event stream messages to/from kafka message brokers cluster.

# Prerequisites {#node-prereq-kafka}

This node-type requires [rdkafka](https://github.com/edenhill/librdkafka) (>= 1.5.0).

# Implementation {#node-implementation-kafka}

The source code of the node-type is available here:
https://git.rwth-aachen.de/acs/public/villas/node/blob/master/lib/nodes/kafka.cpp

# Configuration {#node-config-node-kafka}

## format (string) {#node-config-node-kafka-format}

The payload format which is used to encode and decode exchanged messages.

## server (string) {#node-config-node-kafka-server}

The bootstrap server {ip}:{port} of the Kafka message brokers cluster.

## protocol (string) {#node-config-node-kafka-protocol}

The [security protocol](https://kafka.apache.org/24/javadoc/org/apache/kafka/common/security/auth/SecurityProtocol.html) which is used for authentication with the Kafka cluster.

## client_id (string) {#node-config-node-kafka-client_id}

The Kafka client identifier.

## Example

@include node/etc/examples/nodes/kafka.conf

### CODE REVIEW

**Comment by stv0g** [comment]
Dear @jpnorenam, thanks for your PR. I looks great :) I will merge it in the next couple of days once I am back from vacation.
Please note, that this repository is just a mirror of our main repo here: https://git.rwth-aachen.de/acs/public/villas/node/

But I will take care of merging your commits there. Just to avoid confusion, when I close the PR here.

**Comment by jpnorenam** [comment]
@stv0g thanks, thats great! 

I had to separate producer and consumer clients in the node type. Currently is not working simultaneously in a single node, it seems like some issue with `rd_kafka_new()` method not working for two clients, results in SIGSEGV. Looking forward to contribute more. Best regards.

**Comment by stv0g** [comment]
Hi @jpnorenam,

I started to merge your request here: https://git.rwth-aachen.de/acs/public/villas/node/-/merge_requests/170

The producer / consumer separation could be necessary as VILLASnode might use the Kafka producer and consumers in different threads and therefore cause race conditions if the Kafka library is not multi-threading capable.

**Comment by stv0g** [comment]
Hi @jpnorenam,

I made a few changes to your code. You can see my changes here: https://git.rwth-aachen.de/acs/public/villas/node/-/merge_requests/170/commits

Most of them are just to align the coding style to the rest of the project.
Some are for improving the error handling and logging.

And finally, I might also have fixed your issue with the concurrent use of the producer/consumer.
I assume it was caused by reusing the rdkconf object for two calls to `rd_kafka_new()`.
See: https://git.rwth-aachen.de/acs/public/villas/node/-/merge_requests/170/diffs?commit_id=3f459d353989471c91ea6b254e9de84ce2637e18

Thanks a lot for your contribution :)

**Comment by jpnorenam** [comment]
Hi @stv0g, thank you for solving the issue and merging the kafka node-type, I am so happy to contribute. In the documentation you might include `"PLAINTEXT" `in `{#node-config-node-kafka-protocol}` options.

I'll be trying to make a PR soon with a node-type for IEEE C37.118 synchrophasor protocol. Thanks again.

**Comment by jpnorenam** [comment]
Oh sorry @stv0g , and the `"PLAINTEXT"` option its also missing here https://git.rwth-aachen.de/acs/public/villas/node/-/blob/master/lib/nodes/kafka.cpp#L209-211.

**Comment by stv0g** [comment]
@jpnorenam I added the "PLAINTEXT" option to the documentation 👍 

> Oh sorry @stv0g , and the "PLAINTEXT" option its also missing here https://git.rwth-aachen.de/acs/public/villas/node/-/blob/master/lib/nodes/kafka.cpp#L209-211.

Okay, I will add this as well :)

> I'll be trying to make soon a PR with a node-type for IEEE C37.118 synchrophasor protocol. Thanks again.

Wow thats great to hear :) I am looking forward to merge it. Your coding style is superb

**Comment by stv0g** [comment]
Btw. I am planning to do a proper IEC 61850-8-1 node-type soon. Just in case you might need this one as well :)

**Pull request merged**
